baseURL = 'http://localhost:1313'
languageCode = 'en-us'
title = "rhys-lightning --- DEV"
# theme = "galleriesdeluxe"

[params]
    description = "Rhys Lightning - Go Rhys Lightning!"
    liDivider = " | "

    [params.author]
        name        = "Benjamin Strawbridge"
        email       = "hello@benstraw.com"
        url         = "https://www.benstrawbridge.com"

    [params.galleriesdeluxe]
        # One of dartsass or libsass.
        sass_transpiler = "dartsass"
        [params.galleriesdeluxe.sassvars]
            color_background = "#D32F2F"

    [params.gallerydeluxe]
        enable_click_navigation = true
        shuffle     = false
        reverse     = false 
        enable_exif = false
        # Optional watermark file for the large images.
        [params.gallerydeluxe.watermark]
            image = "images/rhyslightning-watermark.png" # relative to /assets
            posx  = "right"                    # one of "left", "center", "right"
            posy  = "bottom"                  # one of "top", "center", "bottom"

